Table clients {
    client_id integer [pk, increment, note: '顧客ID']
    client_code varchar(20) [not null, unique, note: '顧客コード']
    client_name varchar(100) [not null, note: '顧客名']
    created_at timestamp [not null, note: '作成日時']
    updated_at timestamp [not null, note: '更新日時']

    Note: '顧客情報'
}

Table client_contacts {
    client_contact_id integer [pk, increment, note: '顧客連絡先ID']
    client_id integer [not null, note: '顧客ID']
    postcode varchar(20) [not null, note: '郵便番号']
    address varchar(100) [not null, note: '住所']
    phonenumber varchar(20) [not null, note: '電話番号']
    email varchar(255) [not null, note: 'メールアドレス']
    created_at timestamp [not null, note: '作成日時']
    updated_at timestamp [not null, note: '更新日時']

    Note: '顧客連絡先情報'
}

table products {
    product_id integer [pk, increment, note:'商品ID']
    product_code varchar(20) [not null, unique, note:'商品コード']
    product_name varchar(100) [not null, note:'商品名']
    product_category_id integer [not null, note:'カテゴリID']
    current_unit_price integer [not null, note:'現在販売単価']
    created_at timestamp [not null, note: '作成日時']
    updated_at timestamp [not null, note: '更新日時']

    Note: '商品情報'
}

table product_categories {
    product_category_id integer [pk, increment, note:'カテゴリID']
    product_category_name varchar(100) [not null, note:'商品カテゴリ名']
    created_at timestamp [not null, note: '作成日時']
    updated_at timestamp [not null, note: '更新日時']

    Note: '商品カテゴリ'
}

Table orders {
    order_id integer [pk, increment, note: '注文ID']
    order_number varchar(20) [not null, unique, note: '注文番号']
    order_date date [not null, note: '注文日']
    client_id integer [not null, note: '顧客ID']
    order_status varchar(20) [not null, note: '注文状態:受付済・処理中・完了・キャンセル']
    invoice_id integer [unique,note: '請求ID']
    employee_id integer [not null, note: '社員ID']
    created_at timestamp [not null, note: '作成日時']
    updated_at timestamp [not null, note: '更新日時']

    Note: '注文情報'
}


Table order_details {
    order_detail_id integer [pk, increment, note: '注文明細ID']
    product_id integer [not null, note:'商品ID']
    quantity integer [not null, note: '数量']
    purchase_unit_price integer [not null, note: '購入単価']
    price integer [not null, note: '明細金額']
    product_name_at_order varchar(100) [not null, note:'購入時商品名']
    order_id integer [not null, note: '注文ID']
    created_at timestamp [not null, note: '作成日時']
    updated_at timestamp [not null, note: '更新日時']

    Note: '注文明細情報'
}

Table employees {
    employee_id integer [pk, increment, note: '社員ID']
    employee_name varchar(20) [not null, note: '社員名']
    employee_number varchar(20) [not null, unique, note: '社員番号']
    department_id integer [not null, note:'部署ID']
    created_at timestamp [not null, note: '作成日時']
    updated_at timestamp [not null, note: '更新日時']

    Note: '社員情報'
}

Table invoices {
    invoice_id integer [pk, increment,note: '請求ID']
    invoice_number varchar(20) [not null, unique, note:'請求番号']
    invoice_date date [not null, note: '請求日']
    invoice_due_date date [not null, note: '支払期限']
    invoice_amount integer [not null, note: '請求金額']
    payment_status varchar(20) [not null, note: '請求状態:請求済・一部入金・入金済']
    addressee varchar(100) [not null, note: '宛名']
    postcode varchar(20) [not null, note: '請求時の郵便番号']
    address varchar(100) [not null, note: '請求時の住所']
    created_at timestamp [not null, note: '作成日時']
    updated_at timestamp [not null, note: '更新日時']

    Note: '請求情報'
}

Table deposits {
    deposit_id integer [pk, increment, note: '入金ID']
    deposit_date date [not null, note: '入金日']
    deposit_amount integer [not null, note: '入金金額']
    payment_method varchar(20) [not null, note: '入金方法:銀行振込・クレジットカード・口座振替']
    invoice_id integer [not null,note: '請求ID']
    created_at timestamp [not null, note: '作成日時']
    updated_at timestamp [not null, note: '更新日時']

    Note: '入金情報'
}

Table departments {
    department_id integer [pk, increment, note:'部署ID']
    department_name varchar(20) [not null, note: '部署名']
}


Ref: orders.client_id ?> clients.client_id

Ref: order_details.product_id ?> products.product_id
Ref: order_details.order_id ?> orders.order_id

Ref: products.product_category_id > product_categories.product_category_id

Ref: orders.employee_id ?> employees.employee_id

Ref: employees.department_id ?> departments.department_id

Ref: orders.invoice_id -? invoices.invoice_id

Ref: deposits.invoice_id ?> invoices.invoice_id

Ref: client_contacts.client_id ?> clients.client_id



