//問題4
Table users {
  id int [pk]
  name varchar(100) [not null]
}

Table rooms {
  id int [pk]
  name varchar(100) [not null]
}

Table reservations {
  id int [pk]
  user_id int [not null]
  room_id int [not null]
  starts_at datetime [not null]
}

// ここに必要な Ref: を書く
Ref: reservations.user_id ?> users.id
Ref: reservations.room_id ?> rooms.id

//問題5
Table employees {
  id int [pk]
  name varchar(100) [not null]
}

Table inquiries {
  id int [pk]
  assignee_id int [null]
  subject varchar(200) [not null]
}

Table faq_articles {
  id int [pk]
  title varchar(200) [not null]
}

// ここに必要な Ref: を書く
Ref: inquiries.assignee_id ?>? employees.id